/*
 * Copyright (C) 2019 Mister Wrong <hello@thefoggiest.dev>
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */
package dev.thefoggiest.calcusaurus.view;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.JPanel;

/**
 *
 * @author Mister Wrong <hello@thefoggiest.dev>
 */
public final class BubblePanel extends JPanel
{
    public static String BUBBLE_IMAGE_SE = "src/main/resources/image/bubble-se.png";
    public static String BUBBLE_IMAGE_SW = "src/main/resources/image/bubble-sw.png";
    public static String BUBBLE_IMAGE_NE = "src/main/resources/image/bubble-ne.png";
    public static String BUBBLE_IMAGE_NW = "src/main/resources/image/bubble-nw.png";

    public static Dimension BUBBLE_SIZE = new Dimension(300, 269);
    public static Color TRANSPARENT_BACKGROUND = new Color(0, 0, 0, 0);

    private BufferedImage bubble;

    /**
     * Creates new form BubblePanel
     *
     * @param direction The arrow point direction
     * @param panel The panel
     */
    public BubblePanel(final String direction, final JPanel panel)
    {
        initComponents();
        this.setBackground(TRANSPARENT_BACKGROUND);
        try
        {
            bubble = ImageIO.read(new File(direction));
        } catch (IOException ex)
        {
            System.out.println(ex.getMessage());
        }

        panel.setOpaque(false);
        this.add(panel, BorderLayout.CENTER);
        this.setSize(BUBBLE_SIZE);
    }

    @Override
    protected void paintComponent(Graphics g)
    {
        super.paintComponent(g);
        g.drawImage(bubble, 0, 0, this); // see javadoc for more info on the parameters            
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
