/*
 * Copyright (C) 2019 Mister Wrong <hello@thefoggiest.dev>
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */
package dev.thefoggiest.calcusaurus.view;

import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JCheckBox;
import javax.swing.JPanel;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import dev.thefoggiest.calcusaurus.model.SimpleAdditionAssignment;
import dev.thefoggiest.calcusaurus.model.SimpleDivisionAssignment;
import dev.thefoggiest.calcusaurus.model.SimpleMultiplicationAssignment;
import dev.thefoggiest.calcusaurus.model.SimpleSubstractionAssignment;
import dev.thefoggiest.calcusaurus.util.RequestFocusListener;

/**
 *
 * @author Mister Wrong <hello@thefoggiest.dev>
 */
public class SelectionPanel extends JPanel
{
    private final List<JCheckBox> checkboxes;

    /**
     * Creates new form SelectionPanel
     *
     * @param actionListener
     */
    public SelectionPanel(final ActionListener actionListener)
    {
        initComponents();

        additionCheckBox.setName(SimpleAdditionAssignment.TYPE);
        substractionCheckBox.setName(SimpleSubstractionAssignment.TYPE);
        multiplicationCheckBox.setName(SimpleMultiplicationAssignment.TYPE);
        divisionCheckBox.setName(SimpleDivisionAssignment.TYPE);

        checkboxes = new ArrayList<>();
        checkboxes.add(additionCheckBox);
        checkboxes.add(substractionCheckBox);
        checkboxes.add(multiplicationCheckBox);
        checkboxes.add(divisionCheckBox);

        ChangeListener changeListener = (ChangeEvent ce) ->
        {
            okButton.setEnabled(false);
            checkboxes.stream()
                .filter((checkbox) -> (checkbox.isSelected()))
                .forEach((checkbox) ->
                {
                    okButton.setEnabled(true);
                });
        };

        checkboxes.stream().forEach((checkbox) ->
        {
            checkbox.addChangeListener(changeListener);
        });

        okButton.addActionListener(actionListener);
        okButton.setEnabled(false);
        okButton.addAncestorListener(new RequestFocusListener());
    }

    public List<JCheckBox> getSelection()
    {
        return checkboxes;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        additionCheckBox = new javax.swing.JCheckBox();
        substractionCheckBox = new javax.swing.JCheckBox();
        multiplicationCheckBox = new javax.swing.JCheckBox();
        divisionCheckBox = new javax.swing.JCheckBox();
        okButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setOpaque(false);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Wat wil je doen?");

        additionCheckBox.setText("Optellen");        
        substractionCheckBox.setText("Aftrekken");       
        multiplicationCheckBox.setText("Vermenigvuldigen");
        divisionCheckBox.setText("Delen");
        
        okButton.setText("Ok");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(56, 56, 56))
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(additionCheckBox)
                    .addComponent(substractionCheckBox))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(okButton)
                    .addComponent(multiplicationCheckBox)
                    .addComponent(divisionCheckBox))
                .addContainerGap(118, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(additionCheckBox)
                    .addComponent(multiplicationCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(substractionCheckBox)
                    .addComponent(divisionCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(okButton)
                .addContainerGap(115, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox additionCheckBox;
    private javax.swing.JCheckBox divisionCheckBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JCheckBox multiplicationCheckBox;
    private javax.swing.JButton okButton;
    private javax.swing.JCheckBox substractionCheckBox;
    // End of variables declaration//GEN-END:variables
}
